### PR TITLE
Correct the density of the inverse Wishart distribution in the documentation

### PR DESCRIPTION
**Pull request by willemvandenboom**
Changes to the documentation as suggested in #37

### CODE REVIEW

**Comment by singmann** [comment]
Before I accept this, just one quick question: Did you check whether the implementation is actually correct and not wrong as in teh documentation?

**Comment by willemvandenboom** [comment]
I had not yet checked, but I just did:
The implementations in `dinvwishart` and `dinvwishartc` are already in agreement with the formula of the inverse Wishart density in this pull request.

**Comment by singmann** [comment]
thanks, added. 

Is there any chance you might be interested in addressing or adding pull requests for some of the other open issues? I have never actually used the package so cannot really judge whether these issues are correct.

**Comment by willemvandenboom** [comment]
Thank you for merging and the invite to contribute further. However, I do not use the package much either, and currently do not have the time.

**Pull request merged**
