### PR TITLE
Rlnorm dlnorm

### PR DESCRIPTION
**Pull request by amawl**
I modified the plot function

I fixed the bug (tested locally) for rlnormp and dlnormp. I also added the opportunity to work either with tau (the precision) or the variance var which is 1/tau

### CODE REVIEW

**Comment by singmann** [comment]
Now that you have changed the arguments of `dlnormp` and `plot.demonoid`, you also need to change the documentation of those functions in `man`. Otherwise the package check will throw an error. Can you please add this?

**Comment by amawl** [comment]
Sorry, it should be fine now (at least with regards to the markdown document)

**Comment by singmann** [comment]
I meanwhile added automatic checks. They show the following:
```
Warning: newline within quoted string at plot.demonoid.Rd:44
Error in parse_Rd("/tmp/RtmpRXnzX6/Rbuild39fe7a786097/LaplacesDemon/man/plot.demonoid.Rd",  : 
  Unexpected end of input (in " quoted string opened at plot.demonoid.Rd:44:204)
```
Please fix. And sorry it takes so many steps.

**Comment by singmann** [comment]
Thanks. Added to the package. Please feel free to submit more pull requests if you have the time. I will add you to the author list before the next CRAN submission.

**Pull request merged**
